name: agenomics
description: "AGenomics Claim Checker — Clinical genomics claim verification platform."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.10.0
  get_storage: ^2.1.1
  file_picker: ^11.0.2
  intl: ^0.20.3
  path: ^1.9.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  file_saver: ^0.3.1
  firebase_core: ^4.13.0
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  firebase_messaging: ^16.5.0
  signature: ^6.4.0
  flutter_local_notifications: ^22.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Black.ttf
          weight: 900
